name: Coverage

on: ["push"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Install yuclid build dependencies
      run: sudo apt-get install g++-14 libboost1.83-all-dev libgmp-dev pkg-config
    - name: Set environment variables from .env
      run: cat .env >> "$GITHUB_ENV"
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        uv sync
    - name: Build coverage using pytest-cov
      run: |
        uv run pytest -n auto -m "not slow" --cov --cov-fail-under=74 --cov-report=xml --cov-report=term-missing
    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.xml
