name: Tests

on: ["push"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install yuclid build dependencies
      run: sudo apt-get install g++-14 libboost1.83-all-dev libgmp-dev pkg-config

    - name: Set environment variables from .env
      run: cat .env >> "$GITHUB_ENV"

    - name: Install uv and set the Python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Run pre-commit checks
      uses: pre-commit/action@v3.0.1

    - name: Install dependencies
      run: uv sync --frozen

    - name: type checking newclid
      run: |
        cd newclid/src &&
        uv run mypy .

    - name: Test with pytest
      run: uv run --no-sync pytest -n auto --durations=0 -vv --timeout=24
